import { A11yModule } from '@angular/cdk/a11y';
import { ChangeDetectionStrategy, Component, input, output, inject } from '@angular/core';
import { ToastService } from '../../core/toast.service';
import { SidePanelService } from '../ai/side-panel.service';
import { Avatar, Icon } from '../../shared/ui';
import { CarrierProfile } from './carriers.store';

/** Full carrier profile drawer with a downloadable PDF. */
@Component({
  selector: 'app-carrier-profile-drawer',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [A11yModule, Icon, Avatar],
  templateUrl: './carrier-profile-drawer.html',
  styleUrl: './carrier-profile-drawer.scss',
})
export class CarrierProfileDrawer {
  readonly profile = input<CarrierProfile | null>(null);
  readonly closed = output<void>();

  private readonly toast = inject(ToastService);
  private readonly panel = inject(SidePanelService);

  protected typeLabel(p: CarrierProfile): string { return p.type === 'contracted' ? 'Contracted carrier' : 'Marketplace carrier'; }
  protected message(): void { this.closed.emit(); this.panel.open('messages'); }

  protected async download(): Promise<void> {
    const p = this.profile();
    if (!p) return;
    this.toast.show('Preparing PDF…');
    const { jsPDF } = await import('jspdf');
    const doc = new jsPDF({ unit: 'pt', format: 'a4' });

    // Header band
    doc.setFillColor(34, 50, 103);
    doc.rect(0, 0, 595, 96, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold'); doc.setFontSize(22); doc.text(p.name, 40, 52);
    doc.setFont('helvetica', 'normal'); doc.setFontSize(11);
    doc.text(`${this.typeLabel(p)}  ·  ${p.city}  ·  Madar carrier profile`, 40, 74);

    let y = 140;
    const heading = (t: string) => { doc.setFont('helvetica', 'bold'); doc.setFontSize(13); doc.setTextColor(34, 50, 103); doc.text(t, 40, y); y += 22; };
    const row = (label: string, val: string) => {
      doc.setFont('helvetica', 'normal'); doc.setFontSize(10); doc.setTextColor(120, 125, 140); doc.text(label, 40, y);
      doc.setFontSize(11); doc.setTextColor(31, 39, 51); doc.text(val, 230, y); y += 22;
    };

    heading('Performance');
    row('Rating', `${p.rating} / 5`);
    row('Shipments completed', `${p.shipments}`);
    row('On-time delivery', `${p.onTimePct}%`);
    row('Member since', p.memberSince);
    y += 10;
    heading('Fleet & compliance');
    row('Fleet size', `${p.trucks} trucks`);
    row('Truck types', p.truckTypes);
    row('Years active', `${p.yearsActive} years`);
    row('Verified on Madar', p.verified ? 'Yes' : 'Not yet');
    row('Insured', 'Yes');
    row('TGA licensed', 'Yes');
    y += 10;
    heading('Lanes & contact');
    row('Lanes served', p.lanes);
    row('Contact', p.contactName);
    row('Phone', p.phone);
    row('Email', p.email);

    doc.setFont('helvetica', 'normal'); doc.setFontSize(9); doc.setTextColor(160, 165, 180);
    doc.text('Generated by Madar · Shipper. Figures are indicative and updated per shipment.', 40, 812);

    doc.save(`${p.name.replace(/\s+/g, '-')}-Madar-profile.pdf`);
    this.toast.show('Downloaded profile PDF', 'success');
  }
}
